language: php
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install
script: phpunit --bootstrap bootstrap.php --exclude-group suite tests/
php:
  - 5.3
  - 5.4
